### ISSUE TITLE
Multiple actions - cidr with list

### ISSUE THREAD

**Issue by mzsombor** [tdorssers/confparser#1]
Hello.

First of all thanks for the work you did on this project. I've tried other config parser libraries but your's for some reason is really straightforward to use.

I would like to know if it is possible to apply both the cidr and list actions?

Currently I'm extracting ip addresses from cisco configs using the following dissector:

```
  - match: ip address (?!.*secondary)(?P<ips>.*)
    actionall: cidr
  - match: ip address (?P<ips>.*) secondary
    actionall: cidr
```

In the case of a single primary ip address, without secondary, the result is a string and not a list with a single element.
Currently I have some additional code that checks if the result is a list and if not I convert it, but I thought that this is what the list action does so it would make sense to use it together with the cidr action.

Thank you.

**Comment by tdorssers** [comment]
Thanks! The configs that I use don't have secondary addresses, so I didn't run into this yet, but it makes sense to have cidr output a list.

**Comment by mzsombor** [comment]
Thank you.
