### ISSUE TITLE
Unexpected value when parsing config

### ISSUE THREAD

**Issue by mesmeridze** [tdorssers/confparser#5]
I am trying to pare Arista EOS config, which is mostly Cisco like, however getting unexpected results:
#!/usr/bin/python3
import sys
import confparser

doc = '''
- match: interface (\S+)
  parent: interface
  child:
  - match: load-interval (\S+)
    name: load-interval
  - match: switchport (\S+)
    parent: switchport
    child:
    - match: trunk (\S+)
      parent: trunk
      child:
      - match: native (\S+)
  - match: mlag (\S+)
    name: mlag
'''
cfg = '''
interface Port-Channel1
   load-interval 30
   switchport trunk native vlan 100
   switchport trunk allowed vlan 100,200,300-303,400,500
   switchport mode trunk
   mlag 1
   spanning-tree portfast
!
interface Port-Channel2
   description et-50/1 Core-1-port-0
   load-interval 30
   switchport trunk native vlan 100
   switchport trunk allowed vlan 100,200,300-303,400,500
   switchport mode trunk
   mlag 2
   spanning-tree portfast
!
interface Port-Channel3
   description et-0/0/52-to-Core-2-port-0
   load-interval 30
   switchport trunk native vlan 100
   switchport trunk allowed vlan 100,200,300-303,400,500
   switchport mode trunk
   mlag 3
   spanning-tree portfast
!
'''
print(confparser.Dissector(doc).parse_str(cfg, indent=3))

What I see is this:
{
    "interface": {
        "Port-Channel1": {
            "load-interval": "30",
            "switchport": {
                "trunk": {},
                "mode": {}
            },
            "mlag": "1"
        },
        "Port-Channel2": {
            "load-interval": "30",
            "switchport": {
                "trunk": {},
                "mode": {}
            },
            "mlag": "2"
        },
        "Port-Channel3": {
            "load-interval": "30",
            "switchport": {
                "trunk": {},
                "mode": {}
            },
            "mlag": "3"
        }
    }
}
However I would expect that trunk block should became a key, "native" subkey and "vlan 100" as a value
{
    "interface": {
        "Port-Channel1": {
            "load-interval": "30",
            "switchport": {
                "trunk": {
                   "native": "vlan 100"
                 },
                "mode": "trunk"
            },
            "mlag": "1"
        },
Sorry I am exhausted with ideas, maybe tried all what is possible ))

**Comment by tdorssers** [comment]
You can take a look at ios.yaml, which parses most of your Arista config.
```
- match: interface (\S+)
  parent: interface
  child:
  - match: switchport trunk allowed vlan (?!add)(\S+)
    name: allowed_vlan
    action: expand
  - match: switchport trunk allowed vlan add (\S+)
    name: allowed_vlan
    action: expand
```
will output:
```
{
    "interface": {
        "GigabitEthernet1/1/1": {
            "allowed_vlan": [
                "10",
                "11",
                "12",
                "15"
            ]
        }
    }
}
```
